AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudwatch-alarm-to-slack

  Sample SAM Template for cloudwatch-alarm-to-slack

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        TZ: Asia/Tokyo
        STAGE: PROD
        SLACK_CHANNEL: cloudwatch-alarm
        ENCRYPTED_INCOMING_URL: 
        OK: ":ok:"
        ALARM: ":ng:"
        INSUFFICIENT_DATA: ":question:"
        EXCEPTION: ":rotating_light:"
Resources:
  CloudwatchAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: cloudwatch-alarm-to-slack
      DisplayName: cloudwatch-alarm-to-slack
  CloudwatchAlarmFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: cloudwatch-alarm-to-slack
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Alarm:
          Type: SNS
          Properties:
            Topic: !Ref CloudwatchAlarmTopic
  
  # Sample Cloudwatch Alarm
  ApiCountAlarm:
    Type: AWS::CloudWatch::Alarm # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html
    Properties:
      Namespace: AWS/Api­Gateway
      MetricName: Count
      Dimensions:
        - Name: ApiName
          Value: SampleApi
      Period: 300
      Statistic: Average
      AlarmName: Sample
      AlarmDescription: Sample
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 0
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      OKActions:
        - !Ref CloudwatchAlarmTopic
      AlarmActions:
        - !Ref CloudwatchAlarmTopic
      InsufficientDataActions:
        - !Ref CloudwatchAlarmTopic
